# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.5

# Mod Properties
mod_version=1.0.0+26.2
maven_group=dev.jab125
archives_base_name=touchscreenenhancements

# Dependencies
fabric_version=0.154.0+26.2
